Add Dockerfile
alcmoraes/gramarr pull request #2
Opened 2019-11-12 09:34 UTC by frdmn

Feel free to reject in case you do not want this added in the repository.

2019-12-02 11:37 UTC, joshghent commented
I got the following errors from my Pi (had to change the image to arm32v7/golang:1.13)

Any ideas?

```
Sending build context to Docker daemon  165.9kB
Step 1/6 : FROM arm32v7/golang:1.13
 ---> 19643ce633cc
Step 2/6 : RUN mkdir /app
 ---> Using cache
 ---> c8cecad304d4
Step 3/6 : ADD . /app/
 ---> Using cache
 ---> 46e05afa3757
Step 4/6 : WORKDIR /app
 ---> Using cache
 ---> 58db8088c4a0
Step 5/6 : RUN go build -o gramarr .
 ---> Running in ccb7a657596a
config.go:9:2: cannot find package "github.com/alcmoraes/gramarr/radarr" in any of:
	/usr/local/go/src/github.com/alcmoraes/gramarr/radarr (from $GOROOT)
	/go/src/github.com/alcmoraes/gramarr/radarr (from $GOPATH)
config.go:10:2: cannot find package "github.com/alcmoraes/gramarr/sonarr" in any of:
	/usr/local/go/src/github.com/alcmoraes/gramarr/sonarr (from $GOROOT)
	/go/src/github.com/alcmoraes/gramarr/sonarr (from $GOPATH)
conversation.go:7:2: cannot find package "github.com/patrickmn/go-cache" in any of:
	/usr/local/go/src/github.com/patrickmn/go-cache (from $GOROOT)
	/go/src/github.com/patrickmn/go-cache (from $GOPATH)
conversation.go:6:2: cannot find package "gopkg.in/tucnak/telebot.v2" in any of:
	/usr/local/go/src/gopkg.in/tucnak/telebot.v2 (from $GOROOT)
	/go/src/gopkg.in/tucnak/telebot.v2 (from $GOPATH)
```

2019-12-16 04:04 UTC, adampetrovic commented
The Dockerfile needs to run `go get` before `go build` will work.

```
$ go build -o gramarr .
config.go:9:2: cannot find package "github.com/alcmoraes/gramarr/radarr" in any of:
	/usr/local/Cellar/go/1.13.4/libexec/src/github.com/alcmoraes/gramarr/radarr (from $GOROOT)
	/Users/apetrovic/code/go/src/github.com/alcmoraes/gramarr/radarr (from $GOPATH)
config.go:10:2: cannot find package "github.com/alcmoraes/gramarr/sonarr" in any of:
	/usr/local/Cellar/go/1.13.4/libexec/src/github.com/alcmoraes/gramarr/sonarr (from $GOROOT)
	/Users/apetrovic/code/go/src/github.com/alcmoraes/gramarr/sonarr (from $GOPATH)
conversation.go:7:2: cannot find package "github.com/patrickmn/go-cache" in any of:
	/usr/local/Cellar/go/1.13.4/libexec/src/github.com/patrickmn/go-cache (from $GOROOT)
	/Users/apetrovic/code/go/src/github.com/patrickmn/go-cache (from $GOPATH)
conversation.go:6:2: cannot find package "gopkg.in/tucnak/telebot.v2" in any of:
	/usr/local/Cellar/go/1.13.4/libexec/src/gopkg.in/tucnak/telebot.v2 (from $GOROOT)
	/Users/apetrovic/code/go/src/gopkg.in/tucnak/telebot.v2 (from $GOPATH)
$ go get
$ go build -o gramarr .
```

Alternatively, if the project switches to using modules, then the build command will work.

I have sent up a PR to start using modules: https://github.com/alcmoraes/gramarr/pull/6

2019-12-16 16:05 UTC, frdmn commented
@joshghent Can you retry?

2020-01-13 07:42 UTC, ChaosMarc requested changes
With minor adjustments I was able to test the dockerfile and could run in successfully (Win10 x64 + armhf v7).

2020-01-13 07:42 UTC, ChaosMarc commented on Dockerfile
> +RUN go get
I had to add the following line to be able to build the docker image:
`ENV GOBIN=$GOPATH/bin`

2020-01-13 07:42 UTC, ChaosMarc commented on Dockerfile
> +FROM golang:onbuild
`FROM golang:onbuild`
is deprecated and should be replaced by 
`FROM golang`
or 
`FROM golang:alpine`

2020-02-06 13:10 UTC, merged

2020-02-06 13:15 UTC, alcmoraes commented
Thanks guys! Made a few changes in README as well, tested and its ready to go!